// Cross-language parity: the TS engines must produce deep-equal output to the
// real Python engines (vectors generated by
// artwork_validator/scripts/gen_parity_vectors.py).
import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { LithoValidator } from '../../src/core/validator'
import { mnyConfig, essieConfig } from '../../src/core/brandConfigs'
import type { LithoRecord } from '../../src/core/types'

interface LegacyVector {
  name: string
  brand: 'MNY' | 'ESSIE'
  check_digits: boolean
  pdf_text: string
  excel_data: LithoRecord[]
  expected: unknown
}

interface EnhancedVector extends Omit<LegacyVector, 'expected'> {
  expected: {
    results: unknown[]
    stats: unknown
    errors: string[]
    orphan_tokens: string[]
    summary: unknown
  }
}

const vectors = JSON.parse(
  readFileSync(join(__dirname, '../fixtures/parity/vectors.json'), 'utf-8'),
) as { legacy: LegacyVector[]; enhanced: EnhancedVector[] }

function buildValidator(brand: 'MNY' | 'ESSIE', checkDigits: boolean): LithoValidator {
  const validator = new LithoValidator(brand === 'MNY' ? mnyConfig : essieConfig)
  validator.checkDigits = checkDigits
  return validator
}

describe('parity with Python legacy engine', () => {
  for (const vector of vectors.legacy) {
    it(vector.name, () => {
      const validator = buildValidator(vector.brand, vector.check_digits)
      const results = validator.validate(vector.pdf_text, vector.excel_data)
      expect(results).toEqual(vector.expected)
    })
  }
})

describe('parity with Python enhanced engine', () => {
  for (const vector of vectors.enhanced) {
    it(vector.name, () => {
      const validator = buildValidator(vector.brand, vector.check_digits)
      validator.enhancedValidator.checkDigits = vector.check_digits
      const full = validator.enhancedValidator.validateEnhanced(vector.pdf_text, vector.excel_data)
      expect(full.results).toEqual(vector.expected.results)
      expect(full.stats).toEqual(vector.expected.stats)
      expect(full.errors).toEqual(vector.expected.errors)
      expect(full.orphan_tokens).toEqual(vector.expected.orphan_tokens)
      expect(full.summary).toEqual(vector.expected.summary)
    })
  }
})
