# Cloud Build configuration for deploying to Cloud Run
# Project: proofslab-3f8fe (Firebase + Cloud Run consolidated)
#
# To deploy manually:
#   gcloud builds submit --config cloudbuild.yaml --project=proofslab-3f8fe
#
# Or set up automatic deployment from GitHub in Cloud Console

substitutions:
  _TAG: 'latest'  # Default tag for manual builds

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/proofslab-api:${_TAG}'
      - '.'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/proofslab-api:${_TAG}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'proofslab-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/proofslab-api:${_TAG}'
      - '--region'
      - 'northamerica-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '10'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-secrets'
      - 'FIREBASE_SERVICE_ACCOUNT=firebase-service-account:latest,STRIPE_SECRET_KEY=stripe-secret-key:latest,STRIPE_WEBHOOK_SECRET=stripe-webhook-secret:latest,STRIPE_PRICE_ID_MONTHLY=stripe-price-monthly:latest,STRIPE_PRICE_ID_YEARLY=stripe-price-yearly:latest'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/proofslab-api:${_TAG}'

# Build timeout
timeout: '1200s'
